### ISSUE TITLE
Question about the reference points of the reference and target views

### ISSUE THREAD

**Issue by TingmanYan** [HalleyJiang/RomniStereo#1]
Hi, I have just read your excellent work for omnidirectional stereo matching. RomniStereo uses spherical sweeping and adaptive weighting to extract reference and target feature volume. The front-back and left-right views form virtual reference and target views, respectively.
I have a question about the reference point, i.e., the optical centers of the reference and the target view. How are the two optical centers set up? Are they set as the same point, i.e., the center point of the rig? If so, the stereo baseline of the reference and target view would approximate zero, which is not a wide-baseline setting.
I'm sincerely waiting for your response.

**Comment by HalleyJiang** [comment]
Thanks for the question. It is an important point for RomniStereo. We should clarify that, unlike conventional stereo matching, there is no reference and target view in omnidirectional stereo matching (OSM). In typical stereo matching, the objective is to estimate the disparity/depth map for the physically existing reference view. In contrast, in OSM, the objective is to predict a panoramic depth map for the virtual view at the rig center. The OSM is regarded as a wide-baseline one because of the large physical distance of these four fisheye. To introduce RAFT into OSM, we formulated the reference volume and target volume. They are algorithmic concepts and not a view with a center. In fact, the volume contains depth information, as they are initially obtained with spherical sweeping.

**Comment by TingmanYan** [comment]
Thanks for your reply which has made the concept clear.
